architecture: conv
batch_buffer_size_train: 100
batch_buffer_size_val: 10
batch_size_train: 10
batch_size_val: 100
features:
- JetImage_pixels
train_size: 0.67
weight_expression: Normalization
arch_parameters:
  n_layers_for_conv: 2
  n_filters_for_conv: [32, 32]
  filter_size_for_conv: [3, 3]
  pool_size_for_conv: [2, 2]
  n_layers_for_dense: 5
  n_nodes_for_dense: [128, 128, 64, 64, 32]
  image_shape: [40, 20, 1]
  n_classes: 2
  dropout: 0.4