architecture: conv
training_parameters:
  batch_size: 10
  batch_buffer_size: 1000
  scale_features: norm
  shuffle: true
  train_size: 0.8
validation_parameters:
  batch_size: 1000
  batch_buffer_size: 10
  scale_features: norm
  shuffle: true
weight_expression: weight_total*xs/sumw
features:
- JetImage_pixels
arch_parameters:
  n_layers_for_conv: 1 
  n_filters_for_conv: [4]
  filter_size_for_conv: [4]
  pool_size_for_conv: [2]
  n_layers_for_dense: 1
  n_nodes_for_dense: [100]
  image_shape: [40, 20, 1]
  n_classes: 2
  dropout: 0.2