architecture: dense
training_parameters:
  batch_size: 20
  batch_buffer_size: 1000000
  train_size: 0.5
validation_parameters:
  batch_size: 1000000
  batch_buffer_size: 10
weight_expression: weight_total*xs/sumw
features:
- mjj
- dphijj
- detajj
- mjj_maxmjj
- dphijj_maxmjj
- detajj_maxmjj
- recoil_pt
- dphi_ak40_met
- dphi_ak41_met
- ht
- leadak4_pt
- leadak4_eta
- trailak4_pt
- trailak4_eta
- leadak4_mjjmax_pt
- leadak4_mjjmax_eta
- trailak4_mjjmax_pt
- trailak4_mjjmax_eta
arch_parameters:
  n_layers: 3
  n_nodes: [4, 4, 2]
  dropout: 0.5
  n_classes: 2