features:
  # Which masks we are to run on the feature plots
  # Definitions for each mask are in the script
  run_on:
    - 'Background Like'
    - 'Very Background Like'
  all:
    - 'Signal'
    - 'Background'
    - 'Background Like'
    - 'Very Background Like'
