
name: tests
#Running tests on all branches
on: [push,pull_request]

jobs:
  # This is a job for linux python3 tests
  linuxpy3:
      runs-on: [ubuntu-20.04]
      steps:
        - uses: actions/checkout@v2

        # Install dependencies
        - name: Install python dependencies
          run: |
            curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
            python3 get-pip.py
            python3 -m pip install pytest
        - name: Install ROOT
          run: |
            wget -q https://root.cern/download/root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
            tar xf *tar.gz
            source root/bin/thisroot.sh
        - name: Install this package
          run: |
            python3 -m pip install -e .
        # Run pytest
        - name: Run pytest
          run: |
            source root/bin/thisroot.sh
            python3 -m pytest
