
name: tests
#Running tests on all branches
on: [push,pull_request]

jobs:
  # This is a job for linux python3 tests
  linuxpy3:
      runs-on: [ubuntu-20.04]
      steps:
        - uses: actions/checkout@v2

        # Install dependencies
        - name: Install python dependencies
          run: |
            curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
            python3 get-pip.py
        - name: Install ROOT
          run: |
            wget -q https://root.cern/download/root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
            tar xf *tar.gz
            source root/bin/thisroot.sh
        - name: Install this package
          run: |
            python3 -m pip install -e .

        # Run black code formatter
        - name: black
          run: |
            black --check vbfml

        # Run pytest
        - name: pytest
          run: |
            source root/bin/thisroot.sh
            pip install pytest-cov
            python3 -m pytest --cov=vbfml/

        - name: Upload coverage data to coveralls.io
          run: |
            python -m pip install coveralls==2.2
            coveralls --service=github
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}